### ISSUE TITLE
Multiple hitbox rendering issues

### ISSUE THREAD

**Issue by GoldMario777** [Ploaj/HSDLib#11]
Hitboxes don't scale with the character's ModelScale attribute, resulting in incorrect display. This is best seen with Bowser and Sheik, who use values of 0.69 and 1.4 respectively.

Bowser, HSD:
![BowserFairHSD](https://user-images.githubusercontent.com/61713918/75722432-7d1e8700-5cda-11ea-99b0-80d046aed7d2.png)
Bowser, ingame:
![BowserFairMelee](https://user-images.githubusercontent.com/61713918/75722479-945d7480-5cda-11ea-8218-0601fd66f95e.png)
Sheik, HSD:
![SheikFairHSD](https://user-images.githubusercontent.com/61713918/75722501-9de6dc80-5cda-11ea-911e-8743d1bb307a.png)
Sheik, ingame:
![SheikFairMelee](https://user-images.githubusercontent.com/61713918/75722539-ab03cb80-5cda-11ea-85d1-ff38767cb9eb.png)

Hitboxes also don't read their size value properly, resulting in "snapped" scales. The following picture demonstrates this with an edited version of Mewtwo's Nair, with each hitbox having their respective size stamped on them:
![HitboxSizeCompare](https://user-images.githubusercontent.com/61713918/75722816-3f6e2e00-5cdb-11ea-8d7a-e939403c5e0d.png)
The first two hitboxes are displayed in the same size despite having different values, and so are the last two. Additionally, hitboxes that are very small (<300 units in size) are not rendered at all.

**Comment by Ploaj** [comment]
Fixed in latest
