### ISSUE TITLE
Crash - An item with the same key is already added

### ISSUE THREAD

**Issue by 8bitgentleman** [Ploaj/HSDLib#66]
Upon attempting to open a rootjoint within DAT file map HSDLib keeps crashing with the error `An item with the same key has already been added.`
See the screenshot and the attached error output.
![image](https://user-images.githubusercontent.com/4028391/199564294-ef3db293-d674-4c66-a3c6-b7f7b01906ce.png)
[error.txt](https://github.com/Ploaj/HSDLib/files/9922977/error.txt)

This happens on some files but not others, all from the same batch/game (Mario Kart Arcade GP). Any idea how to fix this or get around it an fully be able to open & export from these files?

**Comment by Ploaj** [comment]
Which files specifically give that error?

**Comment by 8bitgentleman** [comment]
All the files here do. The rest of the GP2 files open just fine
https://mega.nz/folder/sxwCTDSJ#zta6WWEKcO6kdsVufsfK2A

**Comment by Ploaj** [comment]
Should be fixed now.

**Comment by 8bitgentleman** [comment]
Thanks for taking a look at this @Ploaj ! I can now open the models but when trying to export the RootJoint to a dae file a similar error is thrown.
[error.txt](https://github.com/Ploaj/HSDLib/files/10396557/error.txt)
![image](https://user-images.githubusercontent.com/4028391/211935177-d1f7d6bf-87aa-48c3-b617-7bb7a105e9e2.png)
